apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: af-tls
  namespace: default
spec:
  secretName: af-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: af.endpoints.metaverse-363005.cloud.goog
  dnsNames:
  - af.endpoints.metaverse-363005.cloud.goog